// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmDIpeRGGMugTAUQVu3Fq3mIhIn3kR9G4',
    appId: '1:971567006420:web:076816455d8a5c40a3f141',
    messagingSenderId: '971567006420',
    projectId: 'notes-project-database',
    authDomain: 'notes-project-database.firebaseapp.com',
    storageBucket: 'notes-project-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzAVPdeqTO2amwEQmH4rB3ZlSmESUkoBc',
    appId: '1:971567006420:android:21529e4339bb9138a3f141',
    messagingSenderId: '971567006420',
    projectId: 'notes-project-database',
    storageBucket: 'notes-project-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKh_CZZQHmmTkdrAULBJ3zuvvU2QjWwfU',
    appId: '1:971567006420:ios:43e04538fa7cac09a3f141',
    messagingSenderId: '971567006420',
    projectId: 'notes-project-database',
    storageBucket: 'notes-project-database.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKh_CZZQHmmTkdrAULBJ3zuvvU2QjWwfU',
    appId: '1:971567006420:ios:43e04538fa7cac09a3f141',
    messagingSenderId: '971567006420',
    projectId: 'notes-project-database',
    storageBucket: 'notes-project-database.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmDIpeRGGMugTAUQVu3Fq3mIhIn3kR9G4',
    appId: '1:971567006420:web:76a576f082bf9b42a3f141',
    messagingSenderId: '971567006420',
    projectId: 'notes-project-database',
    authDomain: 'notes-project-database.firebaseapp.com',
    storageBucket: 'notes-project-database.firebasestorage.app',
  );
}
